pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://maven.mozilla.org/maven2' }
    }
    
    plugins {
        id 'com.android.application' version '8.9.1'
        // Kotlin 2.2+ required because GeckoView 145 depends on kotlin-stdlib 2.2.20
        id 'org.jetbrains.kotlin.android' version '2.2.0'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.mozilla.org/maven2' }
    }
}

rootProject.name = "BrowserWithExtensions"
include ':app'
