pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://maven.mozilla.org/maven2' }
    }
    
    // Specify plugin versions here so app/build.gradle can reference them without versions
    plugins {
        id 'com.android.application' version '8.5.0'
        id 'org.jetbrains.kotlin.android' version '1.9.23'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.mozilla.org/maven2' }
    }
}

rootProject.name = "BrowserWithExtensions"
include ':app'
